/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VaBlueprintRouteImport } from './routes/va-blueprint'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RefundRouteImport } from './routes/refund'
import { Route as ProgramsRouteImport } from './routes/programs'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiVerifyPaymentRouteImport } from './routes/api/verify-payment'
import { Route as ApiTestEmailRouteImport } from './routes/api/test-email'
import { Route as ApiSendWaitlistNotificationRouteImport } from './routes/api/send-waitlist-notification'
import { Route as ApiSendConfirmationRouteImport } from './routes/api/send-confirmation'
import { Route as ApiSendCareerAssessmentRouteImport } from './routes/api/send-career-assessment'
import { Route as ApiPaystackWebhookRouteImport } from './routes/api/paystack-webhook'

const VaBlueprintRoute = VaBlueprintRouteImport.update({
  id: '/va-blueprint',
  path: '/va-blueprint',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundRoute = RefundRouteImport.update({
  id: '/refund',
  path: '/refund',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsRoute = ProgramsRouteImport.update({
  id: '/programs',
  path: '/programs',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVerifyPaymentRoute = ApiVerifyPaymentRouteImport.update({
  id: '/api/verify-payment',
  path: '/api/verify-payment',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTestEmailRoute = ApiTestEmailRouteImport.update({
  id: '/api/test-email',
  path: '/api/test-email',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSendWaitlistNotificationRoute =
  ApiSendWaitlistNotificationRouteImport.update({
    id: '/api/send-waitlist-notification',
    path: '/api/send-waitlist-notification',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiSendConfirmationRoute = ApiSendConfirmationRouteImport.update({
  id: '/api/send-confirmation',
  path: '/api/send-confirmation',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSendCareerAssessmentRoute = ApiSendCareerAssessmentRouteImport.update({
  id: '/api/send-career-assessment',
  path: '/api/send-career-assessment',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPaystackWebhookRoute = ApiPaystackWebhookRouteImport.update({
  id: '/api/paystack-webhook',
  path: '/api/paystack-webhook',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/privacy': typeof PrivacyRoute
  '/programs': typeof ProgramsRoute
  '/refund': typeof RefundRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/va-blueprint': typeof VaBlueprintRoute
  '/api/paystack-webhook': typeof ApiPaystackWebhookRoute
  '/api/send-career-assessment': typeof ApiSendCareerAssessmentRoute
  '/api/send-confirmation': typeof ApiSendConfirmationRoute
  '/api/send-waitlist-notification': typeof ApiSendWaitlistNotificationRoute
  '/api/test-email': typeof ApiTestEmailRoute
  '/api/verify-payment': typeof ApiVerifyPaymentRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/privacy': typeof PrivacyRoute
  '/programs': typeof ProgramsRoute
  '/refund': typeof RefundRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/va-blueprint': typeof VaBlueprintRoute
  '/api/paystack-webhook': typeof ApiPaystackWebhookRoute
  '/api/send-career-assessment': typeof ApiSendCareerAssessmentRoute
  '/api/send-confirmation': typeof ApiSendConfirmationRoute
  '/api/send-waitlist-notification': typeof ApiSendWaitlistNotificationRoute
  '/api/test-email': typeof ApiTestEmailRoute
  '/api/verify-payment': typeof ApiVerifyPaymentRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/privacy': typeof PrivacyRoute
  '/programs': typeof ProgramsRoute
  '/refund': typeof RefundRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/va-blueprint': typeof VaBlueprintRoute
  '/api/paystack-webhook': typeof ApiPaystackWebhookRoute
  '/api/send-career-assessment': typeof ApiSendCareerAssessmentRoute
  '/api/send-confirmation': typeof ApiSendConfirmationRoute
  '/api/send-waitlist-notification': typeof ApiSendWaitlistNotificationRoute
  '/api/test-email': typeof ApiTestEmailRoute
  '/api/verify-payment': typeof ApiVerifyPaymentRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/privacy'
    | '/programs'
    | '/refund'
    | '/sitemap.xml'
    | '/va-blueprint'
    | '/api/paystack-webhook'
    | '/api/send-career-assessment'
    | '/api/send-confirmation'
    | '/api/send-waitlist-notification'
    | '/api/test-email'
    | '/api/verify-payment'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/privacy'
    | '/programs'
    | '/refund'
    | '/sitemap.xml'
    | '/va-blueprint'
    | '/api/paystack-webhook'
    | '/api/send-career-assessment'
    | '/api/send-confirmation'
    | '/api/send-waitlist-notification'
    | '/api/test-email'
    | '/api/verify-payment'
  id:
    | '__root__'
    | '/'
    | '/privacy'
    | '/programs'
    | '/refund'
    | '/sitemap.xml'
    | '/va-blueprint'
    | '/api/paystack-webhook'
    | '/api/send-career-assessment'
    | '/api/send-confirmation'
    | '/api/send-waitlist-notification'
    | '/api/test-email'
    | '/api/verify-payment'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PrivacyRoute: typeof PrivacyRoute
  ProgramsRoute: typeof ProgramsRoute
  RefundRoute: typeof RefundRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  VaBlueprintRoute: typeof VaBlueprintRoute
  ApiPaystackWebhookRoute: typeof ApiPaystackWebhookRoute
  ApiSendCareerAssessmentRoute: typeof ApiSendCareerAssessmentRoute
  ApiSendConfirmationRoute: typeof ApiSendConfirmationRoute
  ApiSendWaitlistNotificationRoute: typeof ApiSendWaitlistNotificationRoute
  ApiTestEmailRoute: typeof ApiTestEmailRoute
  ApiVerifyPaymentRoute: typeof ApiVerifyPaymentRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/va-blueprint': {
      id: '/va-blueprint'
      path: '/va-blueprint'
      fullPath: '/va-blueprint'
      preLoaderRoute: typeof VaBlueprintRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refund': {
      id: '/refund'
      path: '/refund'
      fullPath: '/refund'
      preLoaderRoute: typeof RefundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs': {
      id: '/programs'
      path: '/programs'
      fullPath: '/programs'
      preLoaderRoute: typeof ProgramsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/verify-payment': {
      id: '/api/verify-payment'
      path: '/api/verify-payment'
      fullPath: '/api/verify-payment'
      preLoaderRoute: typeof ApiVerifyPaymentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/test-email': {
      id: '/api/test-email'
      path: '/api/test-email'
      fullPath: '/api/test-email'
      preLoaderRoute: typeof ApiTestEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/send-waitlist-notification': {
      id: '/api/send-waitlist-notification'
      path: '/api/send-waitlist-notification'
      fullPath: '/api/send-waitlist-notification'
      preLoaderRoute: typeof ApiSendWaitlistNotificationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/send-confirmation': {
      id: '/api/send-confirmation'
      path: '/api/send-confirmation'
      fullPath: '/api/send-confirmation'
      preLoaderRoute: typeof ApiSendConfirmationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/send-career-assessment': {
      id: '/api/send-career-assessment'
      path: '/api/send-career-assessment'
      fullPath: '/api/send-career-assessment'
      preLoaderRoute: typeof ApiSendCareerAssessmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/paystack-webhook': {
      id: '/api/paystack-webhook'
      path: '/api/paystack-webhook'
      fullPath: '/api/paystack-webhook'
      preLoaderRoute: typeof ApiPaystackWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PrivacyRoute: PrivacyRoute,
  ProgramsRoute: ProgramsRoute,
  RefundRoute: RefundRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  VaBlueprintRoute: VaBlueprintRoute,
  ApiPaystackWebhookRoute: ApiPaystackWebhookRoute,
  ApiSendCareerAssessmentRoute: ApiSendCareerAssessmentRoute,
  ApiSendConfirmationRoute: ApiSendConfirmationRoute,
  ApiSendWaitlistNotificationRoute: ApiSendWaitlistNotificationRoute,
  ApiTestEmailRoute: ApiTestEmailRoute,
  ApiVerifyPaymentRoute: ApiVerifyPaymentRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
