/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VaBlueprintRouteImport } from './routes/va-blueprint'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RefundRouteImport } from './routes/refund'
import { Route as RecruitmentRouteImport } from './routes/recruitment'
import { Route as ProgramsRouteImport } from './routes/programs'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiSendConfirmationRouteImport } from './routes/api/send-confirmation'
import { Route as ApiSendCareerAssessmentRouteImport } from './routes/api/send-career-assessment'
import { Route as ApiSendApplicantEmailRouteImport } from './routes/api/send-applicant-email'

const VaBlueprintRoute = VaBlueprintRouteImport.update({
  id: '/va-blueprint',
  path: '/va-blueprint',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundRoute = RefundRouteImport.update({
  id: '/refund',
  path: '/refund',
  getParentRoute: () => rootRouteImport,
} as any)
const RecruitmentRoute = RecruitmentRouteImport.update({
  id: '/recruitment',
  path: '/recruitment',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsRoute = ProgramsRouteImport.update({
  id: '/programs',
  path: '/programs',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSendConfirmationRoute = ApiSendConfirmationRouteImport.update({
  id: '/api/send-confirmation',
  path: '/api/send-confirmation',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSendCareerAssessmentRoute = ApiSendCareerAssessmentRouteImport.update({
  id: '/api/send-career-assessment',
  path: '/api/send-career-assessment',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSendApplicantEmailRoute = ApiSendApplicantEmailRouteImport.update({
  id: '/api/send-applicant-email',
  path: '/api/send-applicant-email',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/privacy': typeof PrivacyRoute
  '/programs': typeof ProgramsRoute
  '/recruitment': typeof RecruitmentRoute
  '/refund': typeof RefundRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/va-blueprint': typeof VaBlueprintRoute
  '/api/send-applicant-email': typeof ApiSendApplicantEmailRoute
  '/api/send-career-assessment': typeof ApiSendCareerAssessmentRoute
  '/api/send-confirmation': typeof ApiSendConfirmationRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/privacy': typeof PrivacyRoute
  '/programs': typeof ProgramsRoute
  '/recruitment': typeof RecruitmentRoute
  '/refund': typeof RefundRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/va-blueprint': typeof VaBlueprintRoute
  '/api/send-applicant-email': typeof ApiSendApplicantEmailRoute
  '/api/send-career-assessment': typeof ApiSendCareerAssessmentRoute
  '/api/send-confirmation': typeof ApiSendConfirmationRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/privacy': typeof PrivacyRoute
  '/programs': typeof ProgramsRoute
  '/recruitment': typeof RecruitmentRoute
  '/refund': typeof RefundRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/va-blueprint': typeof VaBlueprintRoute
  '/api/send-applicant-email': typeof ApiSendApplicantEmailRoute
  '/api/send-career-assessment': typeof ApiSendCareerAssessmentRoute
  '/api/send-confirmation': typeof ApiSendConfirmationRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/privacy'
    | '/programs'
    | '/recruitment'
    | '/refund'
    | '/sitemap.xml'
    | '/va-blueprint'
    | '/api/send-applicant-email'
    | '/api/send-career-assessment'
    | '/api/send-confirmation'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/privacy'
    | '/programs'
    | '/recruitment'
    | '/refund'
    | '/sitemap.xml'
    | '/va-blueprint'
    | '/api/send-applicant-email'
    | '/api/send-career-assessment'
    | '/api/send-confirmation'
  id:
    | '__root__'
    | '/'
    | '/privacy'
    | '/programs'
    | '/recruitment'
    | '/refund'
    | '/sitemap.xml'
    | '/va-blueprint'
    | '/api/send-applicant-email'
    | '/api/send-career-assessment'
    | '/api/send-confirmation'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PrivacyRoute: typeof PrivacyRoute
  ProgramsRoute: typeof ProgramsRoute
  RecruitmentRoute: typeof RecruitmentRoute
  RefundRoute: typeof RefundRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  VaBlueprintRoute: typeof VaBlueprintRoute
  ApiSendApplicantEmailRoute: typeof ApiSendApplicantEmailRoute
  ApiSendCareerAssessmentRoute: typeof ApiSendCareerAssessmentRoute
  ApiSendConfirmationRoute: typeof ApiSendConfirmationRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/va-blueprint': {
      id: '/va-blueprint'
      path: '/va-blueprint'
      fullPath: '/va-blueprint'
      preLoaderRoute: typeof VaBlueprintRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refund': {
      id: '/refund'
      path: '/refund'
      fullPath: '/refund'
      preLoaderRoute: typeof RefundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recruitment': {
      id: '/recruitment'
      path: '/recruitment'
      fullPath: '/recruitment'
      preLoaderRoute: typeof RecruitmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs': {
      id: '/programs'
      path: '/programs'
      fullPath: '/programs'
      preLoaderRoute: typeof ProgramsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/send-confirmation': {
      id: '/api/send-confirmation'
      path: '/api/send-confirmation'
      fullPath: '/api/send-confirmation'
      preLoaderRoute: typeof ApiSendConfirmationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/send-career-assessment': {
      id: '/api/send-career-assessment'
      path: '/api/send-career-assessment'
      fullPath: '/api/send-career-assessment'
      preLoaderRoute: typeof ApiSendCareerAssessmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/send-applicant-email': {
      id: '/api/send-applicant-email'
      path: '/api/send-applicant-email'
      fullPath: '/api/send-applicant-email'
      preLoaderRoute: typeof ApiSendApplicantEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PrivacyRoute: PrivacyRoute,
  ProgramsRoute: ProgramsRoute,
  RecruitmentRoute: RecruitmentRoute,
  RefundRoute: RefundRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  VaBlueprintRoute: VaBlueprintRoute,
  ApiSendApplicantEmailRoute: ApiSendApplicantEmailRoute,
  ApiSendCareerAssessmentRoute: ApiSendCareerAssessmentRoute,
  ApiSendConfirmationRoute: ApiSendConfirmationRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
